---
 
- name: Install Cclickhouse
  hosts: clickhouse
  tags: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  tags: vector
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  tags: lighthouse
  pre_tasks:
    - name: Install dependencies
      become: true
      become_user: root
      ansible.builtin.yum:
        name: 
        - git
        - nginx
        state: present
  roles:
    - lighthouse
